#!/bin/sh
set -e

source ./util.sh

# Ensure the required variables are present
checkVars -p HOOK_ \
    repo \
    branch \
    build_status \
    build_number \
    build_started \
    build_finished \
    build_link \
    commit \
    commit_link \
    commit_message \
        || exit $?

# Construct the notification message
secs="$(expr $HOOK_build_finished - $HOOK_build_started)"
message="*$HOOK_repo [$HOOK_branch]* #$HOOK_build_number: *$(upper $HOOK_build_status)* in $(date -u -d @$secs '+%Mm %Ss')
[$HOOK_build_link]($HOOK_build_link)
[#${HOOK_commit:0:7}]($HOOK_commit_link): _${HOOK_commit_message}_"

# Send the message with the telegram api
telegram-api sendMessage "$message" "disable_web_page_preview=true"
