#!/bin/sh
set -e

source ./util.sh

# Ensure the required variables are present
checkVars -p HOOK_ \
    repo \
    branch \
    status \
    build_num \
    build_started \
    build_finished \
    url \
    commit \
    commit_url \
    commit_msg \
        || exit $?

# Construct the notification message
secs="$(expr $HOOK_build_finished - $HOOK_build_started)"
message="*$HOOK_repo [$HOOK_branch]* #$HOOK_build_num: *$(upper $HOOK_status)* in $(date -u -d @$secs '+%Mm %Ss')
[$HOOK_url]($HOOK_url)
[#${HOOK_commit:0:7}]($HOOK_commit_url): _${HOOK_commit_msg}_"

# Send the message with the telegram api
telegram-api sendMessage "$message" "disable_web_page_preview=true"
