#!/bin/sh
set -e

source ./util.sh

TELEGRAM_API="https://api.telegram.org"

# buildUrl <token> <method>
buildUrl() { echo "${TELEGRAM_API}/bot${1}/${2}"; }

# buildMessage <message> <optional args>
sendMessagePayload() {
    [ -z "$1" ] && logwarn "No message argument specified"
    [ -z "$TELEGRAM_CHAT_ID" ] && logwarn "No TELEGRAM_CHAT_ID specified"
    text="$1"; shift || true
    jo parse_mode=HTML "chat_id=$TELEGRAM_CHAT_ID" "text=$text" "$@"
}

# callAPI <token> <method> <args>
callAPI() {
    output="$(IFS=$'\n'; curl $CURL_OPTS -X POST -H "Content-Type: application/json" --data "$3" "$(buildUrl "$1" "$2")")"
    [ -n "$output" ] && loginfo "$output"
}

[ -z "$TELEGRAM_BOT_TOKEN" ] && logwarn "No TELEGRAM_BOT_TOKEN specified"

command="$(echo "$1" | tr A-Z a-z)"
shift || true

case $command in
    msg|message|sendmessage)
        payload="$(sendMessagePayload "$@")" || exit 1
        callAPI "$TELEGRAM_BOT_TOKEN" "sendMessage" "$payload" \
            || logwarn "telegram sendMessage failed";;
    get|getme)
        callAPI "$TELEGRAM_BOT_TOKEN" "getMe" \
            || logwarn "telegram getMe failed";;
    *)
        >&2 echo -e "Usage: $(basename "$0") <command> [args..]\n\nCOMMANDS:\n\tmessage\t\tSends a message (arg) to \$CHAT_ID\n\tgetme\t\tGets the bot information\n"
        exit 99;;
esac

