#!/bin/sh
set -e

source ./util.sh

TELEGRAM_API="https://api.telegram.org"

# buildUrl <token> <method>
buildUrl() { echo "${TELEGRAM_API}/bot${1}/${2}"; }

# buildMessage <message> <optional args>
sendMessagePayload() {
    [ -z "$1" ]       && error "No message argument specified"
    [ -z "$TELEGRAM_CHAT_ID" ] && error "No TELEGRAM_CHAT_ID specified"
    jo parse_mode=markdown "chat_id=$TELEGRAM_CHAT_ID" "text=$1" "$@"
}

# callAPI <token> <method> <data>
callAPI() { curl -X POST -H "Content-Type: application/json" --data "$3" "$(buildUrl "$1" "$2")"; }


[ -z "$TELEGRAM_BOT_TOKEN" ] && error "No TELEGRAM_BOT_TOKEN specified"

command="$(echo "$1" | tr A-Z a-z)"
shift || true

case $command in
    msg|message|sendmessage)
        payload="$(sendMessagePayload "$@")" || exit 1
        callAPI "$TELEGRAM_BOT_TOKEN" "sendMessage" "$payload";;
    get|getme)
        callAPI "$TELEGRAM_BOT_TOKEN" "getMe";;
    *)
        >&2 echo -e "Usage: $(basename "$0") <command> [args..]\n\nCOMMANDS:\n\tmessage\t\tSends a message (arg) to \$CHAT_ID\n\tgetme\t\tGets the bot information\n"
        exit 99;;
esac

